version: '3.8'

services:
  instagram-scraper:
    image: sandeepseeram22/instagram-scraper:latest
    container_name: instagram-scraper-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PM2_HOME=/app/.pm2
    volumes:
      # Volume for storing session data
      - instagram_sessions:/app/src/sessions
      # Volume for PM2 logs
      - pm2_logs:/app/logs
      # Volume for persistent data
      - app_data:/app/data
    restart: unless-stopped
    # Add healthcheck to ensure service is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Security options
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem for security
    read_only: false
    # Temporary filesystem for /tmp
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

volumes:
  instagram_sessions:
    driver: local
  pm2_logs:
    driver: local
  app_data:
    driver: local

networks:
  default:
    driver: bridge 