version: '3.8'

services:
  instagram-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    image: instagram-scraper:latest
    container_name: instagram-scraper
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PM2_HOME=/app/.pm2
    volumes:
      - .:/app
      - /app/node_modules
      # Volume for storing session data
      - instagram_sessions:/app/src/sessions
      # Volume for PM2 logs
      - pm2_logs:/app/logs
    restart: unless-stopped
    # Add healthcheck to ensure service is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  instagram_sessions:
    driver: local
  pm2_logs:
    driver: local 